#ifndef WEBUI_DATA_C
#define WEBUI_DATA_C

const char webui_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"  <meta charset=\"UTF-8\">"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"  <title>Multi-Channel Temperature Controller</title>"
"  <link rel=\"stylesheet\" href=\"/style.css\">"
"</head>"
"<body>"
"  <div id=\"app\">"
"    <header>"
"      <h1>Temperature Controller</h1>"
"      <div id=\"status-bar\">"
"        <span id=\"sys-state\">State: --</span>"
"        <span id=\"sys-uptime\">Uptime: --</span>"
"        <span id=\"sys-alarms\" class=\"alarm-off\">Alarms: 0</span>"
"      </div>"
"    </header>"
"    <main>"
"      <section id=\"sensors-panel\">"
"        <h2>Sensor Readings</h2>"
"        <div id=\"sensor-grid\"></div>"
"      </section>"
"      <section id=\"pid-panel\">"
"        <h2>PID Control Channels</h2>"
"        <div id=\"pid-grid\"></div>"
"      </section>"
"      <section id=\"output-panel\">"
"        <h2>Output Channels</h2>"
"        <div id=\"output-grid\"></div>"
"      </section>"
"      <section id=\"trend-panel\">"
"        <h2>Real-Time Temperature Trends</h2>"
"        <canvas id=\"trend-chart\" width=\"800\" height=\"300\"></canvas>"
"      </section>"
"    </main>"
"    <footer>STM32 Multi-Channel Temp Controller v1.0</footer>"
"  </div>"
"  <script src=\"/app.js\"></script>"
"</body>"
"</html>";

const char webui_css[] =
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:#0d1117;color:#c9d1d9;font-size:14px}"
"#app{max-width:1200px;margin:0 auto;padding:16px}"
"header{display:flex;justify-content:space-between;align-items:center;padding:12px 20px;background:#161b22;border-bottom:2px solid #30363d;margin-bottom:16px;border-radius:6px}"
"header h1{font-size:18px;color:#58a6ff}"
"#status-bar{display:flex;gap:16px;font-size:12px}"
"#status-bar span{padding:4px 10px;background:#21262d;border-radius:4px}"
".alarm-off{color:#3fb950}.alarm-on{color:#f85149;animation:blink 0.5s infinite}"
"@keyframes blink{50%{opacity:0.5}}"
"section{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px;margin-bottom:16px}"
"section h2{font-size:16px;color:#58a6ff;margin-bottom:12px;border-bottom:1px solid #30363d;padding-bottom:8px}"
"#sensor-grid,#pid-grid,#output-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}"
".sensor-card,.pid-card,.output-card{background:#21262d;border:1px solid #30363d;border-radius:6px;padding:12px}"
".sensor-card h3,.pid-card h3,.output-card h3{font-size:13px;color:#8b949e;margin-bottom:8px}"
".temp-value{font-size:32px;font-weight:bold;color:#58a6ff}"
".temp-value.fault{color:#f85149}"
".pid-card .sp-label{font-size:12px;color:#8b949e;margin-top:4px}"
".pid-card .output-bar{height:6px;background:#30363d;border-radius:3px;margin-top:8px;overflow:hidden}"
".pid-card .output-bar-fill{height:100%;background:#3fb950;border-radius:3px;transition:width 0.3s}"
".pid-card .tuning-info{font-size:11px;color:#8b949e;margin-top:6px}"
".pid-card button,.output-card button{font-size:11px;padding:4px 10px;border:1px solid #30363d;border-radius:4px;background:#21262d;color:#c9d1d9;cursor:pointer;margin:4px 2px}"
".pid-card button:hover{background:#30363d}"
".pid-card button.active{background:#238636;border-color:#238636;color:#fff}"
".output-card .output-bar{height:8px;background:#30363d;border-radius:4px;margin-top:6px;overflow:hidden}"
".output-card .output-bar-fill{height:100%;background:#d2991d;border-radius:4px}"
"#trend-panel{position:relative}"
"#trend-chart{width:100%;height:300px;background:#0d1117;border-radius:4px}"
"footer{text-align:center;color:#484f58;font-size:11px;margin-top:16px;padding:12px}"
"input[type=\"number\"]{width:70px;padding:4px;background:#0d1117;color:#c9d1d9;border:1px solid #30363d;border-radius:4px;font-size:12px}"
".fault-indicator{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}"
".fault-ok{background:#3fb950}.fault-bad{background:#f85149}";

const char webui_js[] =
"window.addEventListener('DOMContentLoaded',function(){"
  "var hist={ch1:[],ch2:[],ch3:[],ch4:[]};"
  "var maxPoints=200;"
  "var pollInterval=1000;"

  "function fetchData(){"
    "var xhr=new XMLHttpRequest();"
    "xhr.open('GET','/api/data',true);"
    "xhr.onload=function(){"
      "if(xhr.status===200){"
        "try{"
          "var data=JSON.parse(xhr.responseText);"
          "renderSensors(data.sensors);"
          "renderPID(data.pid_channels);"
          "renderOutputs(data.outputs);"
          "renderSystem(data.system,data.uptime_ms);"
          "updateTrend(data.pid_channels);"
        "}catch(e){console.error(e)}"
      "}"
    "};"
    "xhr.onerror=function(){console.error('XHR error')};"
    "xhr.send()"
  "}"

  "function renderSensors(sensors){"
    "var grid=document.getElementById('sensor-grid');"
    "grid.innerHTML='';"
    "sensors.forEach(function(s){"
      "var card=document.createElement('div');"
      "card.className='sensor-card';"
      "var faultClass=s.fault===0?'fault-ok':'fault-bad';"
      "var tempClass=s.valid?'temp-value':'temp-value fault';"
      "card.innerHTML='<h3><span class=\"fault-indicator '+faultClass+'\"></span>Sensor '+s.ch+'</h3>'+"
        "'<div class=\"'+tempClass+'\">'+s.temp.toFixed(1)+'°C</div>'+"
        "'<div style=\"font-size:11px;color:#8b949e\">CJ: '+s.cj.toFixed(1)+'°C | Fault: '+s.fault+'</div>';"
      "grid.appendChild(card)"
    "})"
  "}"

  "function renderPID(channels){"
    "var grid=document.getElementById('pid-grid');"
    "grid.innerHTML='';"
    "channels.forEach(function(p){"
      "var card=document.createElement('div');"
      "card.className='pid-card';"
      "card.innerHTML='<h3>PID Channel '+p.ch+' (Sensor '+p.sensor_idx+')</h3>'+"
        "'<div>SP: <input type=\"number\" value=\"'+p.sp.toFixed(1)+'\" onchange=\"updateSP('+p.ch+',this.value)\" step=\"0.5\"> °C</div>'+"
        "'<div class=\"output-bar\"><div class=\"output-bar-fill\" style=\"width:'+p.output+'%\"></div></div>'+"
        "'<div style=\"font-size:13px\">Output: '+p.output.toFixed(1)+'% | Mode: '+p.mode+'</div>'+"
        "'<div class=\"tuning-info\">Kp='+p.kp.toFixed(4)+' Ki='+p.ki.toFixed(4)+' Kd='+p.kd.toFixed(4)+'</div>'+"
        "'<button class=\"'+(p.mode==='auto'?'active':'')+'\" onclick=\"toggleMode('+p.ch+')\">'+p.mode.toUpperCase()+'</button>'+"
        "'<button onclick=\"autoTune('+p.ch+',1)\">Auto-Tune Z-N</button>'+"
        "'<button onclick=\"autoTune('+p.ch+',2)\">Auto-Tune C-C</button>';"
      "card.id='pid-card-'+p.ch;"
      "grid.appendChild(card)"
    "})"
  "}"

  "function renderOutputs(outputs){"
    "var grid=document.getElementById('output-grid');"
    "grid.innerHTML='';"
    "outputs.forEach(function(o){"
      "var card=document.createElement('div');"
      "card.className='output-card';"
      "card.innerHTML='<h3>Output '+o.ch+'</h3>'+"
        "'<div class=\"output-bar\"><div class=\"output-bar-fill\" style=\"width:'+o.duty+'%\"></div></div>'+"
        "'<div>Duty: '+o.duty.toFixed(1)+'% | '+(o.enabled?'ENABLED':'DISABLED')+'</div>';"
      "grid.appendChild(card)"
    "})"
  "}"

  "function renderSystem(sys,uptime){"
    "var stateEl=document.getElementById('sys-state');"
    "var states=['INIT','IDLE','RUNNING','FAULT','EMERGENCY'];"
    "stateEl.textContent='State: '+(states[sys.state]||'UNKNOWN');"
    "if(sys.emergency){stateEl.style.color='#f85149'}else{stateEl.style.color='#c9d1d9'}"
    "var alarmEl=document.getElementById('sys-alarms');"
    "alarmEl.textContent='Alarms: '+sys.alarms;"
    "alarmEl.className=sys.alarms>0?'alarm-on':'alarm-off';"
    "var uptimeEl=document.getElementById('sys-uptime');"
    "uptimeEl.textContent='Uptime: '+(uptime/1000).toFixed(1)+'s'"
  "}"

  "function updateTrend(channels){"
    "channels.forEach(function(p){"
      "var h=hist['ch'+p.ch];"
      "h.push(p.sp);"
      "if(h.length>maxPoints)h.shift();"
    "});"
    "drawChart()"
  "}"

  "function drawChart(){"
    "var canvas=document.getElementById('trend-chart');"
    "var ctx=canvas.getContext('2d');"
    "var w=canvas.width;var h=canvas.height;"
    "ctx.fillStyle='#0d1117';ctx.fillRect(0,0,w,h);"
    "ctx.strokeStyle='#30363d';ctx.lineWidth=1;"
    "for(var i=0;i<5;i++){var y=(h/5)*i;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}"
    "var colors=['#58a6ff','#3fb950','#d2991d','#f85149'];"
    "for(var ch=1;ch<=4;ch++){"
      "var data=hist['ch'+ch]||[];"
      "if(data.length<2)continue;"
      "ctx.strokeStyle=colors[ch-1];ctx.lineWidth=2;"
      "ctx.beginPath();"
      "for(var i=0;i<data.length;i++){"
        "var x=(i/data.length)*w;"
        "var y=h-((data[i]/450)*h);"
        "if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)"
      "}"
      "ctx.stroke()"
    "}"
    "ctx.fillStyle='#8b949e';ctx.font='10px monospace';"
    "ctx.fillText('0°C',2,h-4);ctx.fillText('450°C',2,12)"
  "}"

  "window.toggleMode=function(ch){"
    "var xhr=new XMLHttpRequest();"
    "xhr.open('POST','/api/control?ch='+ch+'&action=toggle_mode',true);"
    "xhr.send()"
  "};"

  "window.updateSP=function(ch,val){"
    "var xhr=new XMLHttpRequest();"
    "xhr.open('POST','/api/control?ch='+ch+'&action=setpoint&value='+parseFloat(val),true);"
    "xhr.send()"
  "};"

  "window.autoTune=function(ch,method){"
    "var xhr=new XMLHttpRequest();"
    "xhr.open('GET','/api/autotune?ch='+ch+'&cmd='+method,true);"
    "xhr.onload=function(){"
      "try{var r=JSON.parse(xhr.responseText);console.log('Auto-tune:',r)}catch(e){}"
    "};"
    "xhr.send()"
  "};"

  "fetchData();"
  "setInterval(fetchData,pollInterval)"
"});";

#endif /* WEBUI_DATA_C */
